### ISSUE TITLE
This line can be removed

### ISSUE THREAD

**Issue by ddigulescu** [denisagm/iQuest-Remote-Learning#3]
https://github.com/denisagm/iQuest-Remote-Learning/blob/5ada221b2d4e9374c308290426c139f483e3c07a/Homework%201/Homework%201.html#L5

**Comment by denisagm** [comment]
The line was mandatory in the requirements
![image](https://user-images.githubusercontent.com/33956274/37173663-ddacdd50-231c-11e8-8162-69992f713052.png)
